# Generated by Django 4.2.3 on 2023-07-27 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_posts_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='image',
        ),
    ]
